# Generated by Django 2.1.1 on 2018-10-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betchyaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teamb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_B', to='betchyaApp.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
    ]
